import { Word, WordGroup, Article } from './types';

/**
 * 【 AceEnglish Pro 数据映射表 - 全量恢复版 】
 * 锁定状态：Group 1-6, Group 10-15 (locked = true)
 * 规则：JSON 为唯一事实源，恢复之前被简化的学术、商务与科技词库。
 */

export const WORDS: Word[] = [
  // --- Group 1 (Locked) ---
  { id: 'w101', text: 'allocate', phonetic: '', pos: 'v.', definition: 'to distribute (resources or duties) for a particular purpose', chinese: '分配', categories: [], examples: [{ en: "The company will allocate more funds to the marketing department next year.", cn: "公司明年将分配更多资金给市场部。" }, { en: "How did you allocate your time between work and study?", cn: "你是如何分配工作 and 学习时间的？" }] },
  { id: 'w102', text: 'ambiguous', phonetic: '', pos: 'adj.', definition: 'open to more than one interpretation; unclear', chinese: '模棱两可，含糊不清', categories: [], examples: [{ en: "His reply was ambiguous and didn’t clarify the situation.", cn: "他的回答模棱两可，没有澄清情况。" }, { en: "The contract contains some ambiguous terms that need to be revised.", cn: "合同中有一些含糊不清的条款需要修改。" }] },
  { id: 'w103', text: 'benevolent', phonetic: '', pos: 'adj.', definition: 'well meaning and kindly', chinese: '仁慈的', categories: [], examples: [{ en: "She is known for her benevolent attitude toward the poor.", cn: "她以对穷人的仁慈态度而闻名。" }, { en: "The benevolent donor gave millions to the children’s hospital.", cn: "这位仁慈的捐赠者向儿童医院捐赠了数百万元。" }] },
  { id: 'w104', text: 'consensus', phonetic: '', pos: 'n.', definition: 'general agreement', chinese: '共识，一致认为', categories: [], examples: [{ en: "After much discussion, the team reached a consensus on the project plan.", cn: "经过多次讨论，团队就项目计划达成共识。" }, { en: "There is a growing consensus that climate change must be addressed urgently.", cn: "人们越来越一致认为气候变化必须紧急应对。" }] },
  { id: 'w105', text: 'deteriorate', phonetic: '', pos: 'v.', definition: 'to become progressively worse', chinese: '恶化', categories: [], examples: [{ en: "The political situation in the region has deteriorated rapidly.", cn: "该地区的政治局势迅速恶化。" }, { en: "Without proper maintenance, the building’s condition will deteriorate.", cn: "没有适当的维护，大楼的状况会恶化。" }] },
  { id: 'w106', text: 'entrepreneur', phonetic: '', pos: 'n.', definition: 'a person who starts a business and is willing to risk loss in order to make money', chinese: '企业家', categories: [], examples: [{ en: "She is a successful entrepreneur who founded three tech startups.", cn: "她是一位成功的企业家，创办了三家科技初创公司。" }, { en: "Entrepreneurs often face financial challenges in the early stages of their ventures.", cn: "企业家在创业初期常面临财务挑战。" }] },
  { id: 'w107', text: 'feasible', phonetic: '', pos: 'adj.', definition: 'possible to do easily or conveniently', chinese: '可行的', categories: [], examples: [{ en: "The plan sounds feasible, but we need to check the budget.", cn: "这个计划听起来可行，但我们需要核对预算。" }, { en: "Is it feasible to complete the report by Friday?", cn: "周五前完成报告可行吗？" }] },
  { id: 'w108', text: 'hypothesis', phonetic: '', pos: 'n.', definition: 'a supposition or proposed explanation made on the basis of limited evidence', chinese: '假设', categories: [], examples: [{ en: "Scientists tested the hypothesis that the drug would reduce symptoms.", cn: "科学家测试了这种药物能减轻症状的假设。" }, { en: "Her hypothesis about customer behavior was later confirmed by data.", cn: "她关于顾客行为的假设后来被数据证实。" }] },
  { id: 'w109', text: 'integrity', phonetic: '', pos: 'n.', definition: 'the quality of being honest and having strong moral principles; the state of being whole and undivided', chinese: '诚信，完整性', categories: [], examples: [{ en: "He is a man of great integrity and would never lie to his clients.", cn: "他是一个极其诚信的人，绝不会对客户撒谎。" }, { en: "The integrity of the data must be protected from unauthorized access.", cn: "数据的完整性必须受到保护，防止未经授权的访问。" }] },
  { id: 'w110', text: 'juxtapose', phonetic: '', pos: 'v.', definition: 'to place or deal with close together for contrasting effect', chinese: '并列', categories: [], examples: [{ en: "The exhibition juxtaposes modern art with classical sculptures.", cn: "展览将现代艺术与古典雕塑并列展出。" }, { en: "By juxtaposing the two images, the photographer highlights their differences.", cn: "通过将两幅图像并列，摄影师突出了它们的差异。" }] },
  { id: 'w111', text: 'lucrative', phonetic: '', pos: 'adj.', definition: 'producing a great deal of profit', chinese: '有利可图的', categories: [], examples: [{ en: "He left his job to pursue a more lucrative career in finance.", cn: "他辞去工作，转而从事更有利可图的金融职业。" }, { en: "Real estate can be a lucrative investment if you choose the right location.", cn: "如果选对地点，房地产可能是一项利润丰厚的投资。" }] },
  { id: 'w112', text: 'mitigate', phonetic: '', pos: 'v.', definition: 'to make less severe, serious, or painful', chinese: '减轻', categories: [], examples: [{ en: "Planting trees can help mitigate the effects of climate change.", cn: "植树有助于减轻气候变化的影响。" }, { en: "The company took steps to mitigate the risks associated with the new project.", cn: "公司采取措施减轻与新项目相关的风险。" }] },
  { id: 'w113', text: 'nostalgia', phonetic: '', pos: 'n.', definition: 'a sentimental longing for the past', chinese: '怀旧', categories: [], examples: [{ en: "The old song filled her with nostalgia for her college days.", cn: "那首老歌让她充满了对大学时光的怀念。" }, { en: "There’s a sense of nostalgia in the town’s traditional festivals.", cn: "小镇的传统节日中有一种怀旧感。" }] },
  { id: 'w114', text: 'paradigm', phonetic: '', pos: 'n.', definition: 'a typical example or pattern of something; a model', chinese: '范式，范例', categories: [], examples: [{ en: "The discovery led to a paradigm shift in scientific thinking.", cn: "这一发现导致了科学思维的范式转变。" }, { en: "This case will serve as a paradigm for future legal disputes.", cn: "这个案例将成为未来法律纠纷的范例。" }] },
  { id: 'w115', text: 'quantitative', phonetic: '', pos: 'adj.', definition: 'relating to, measuring, or measured by the quantity of something', chinese: '定量的', categories: [], examples: [{ en: "The study uses quantitative data to analyze economic trends.", cn: "该研究使用定量数据分析经济趋势。" }, { en: "Quantitative analysis is essential in financial modeling.", cn: "定量分析在金融建模中至关重要。" }] },
  { id: 'w116', text: 'resilient', phonetic: '', pos: 'adj.', definition: 'able to withstand or recover quickly from difficult conditions', chinese: '有韧性的', categories: [], examples: [{ en: "Children are often more resilient than adults think.", cn: "孩子们通常比成年人想象的更有韧性。" }, { en: "The economy has shown itself to be resilient despite global challenges.", cn: "尽管面临全球挑战，经济已显示出其韧性。" }] },
  { id: 'w117', text: 'sustainable', phonetic: '', pos: 'adj.', definition: 'able to be maintained at a certain rate or level; conserving an ecological balance', chinese: '可持续的', categories: [], examples: [{ en: "We need to find sustainable sources of energy.", cn: "我们需要找到可持续的能源。" }, { en: "The company is committed to sustainable business practices.", cn: "公司致力于可持续的商业实践。" }] },
  { id: 'w118', text: 'tentative', phonetic: '', pos: 'adj.', definition: 'not certain or fixed; provisional', chinese: '暂定的', categories: [], examples: [{ en: "We’ve made a tentative agreement, but the details still need to be finalized.", cn: "我们达成了一个暂定协议，但细节仍需敲定。" }, { en: "She gave a tentative smile, unsure of how he would react.", cn: "她试探性地笑了笑，不确定他会作何反应。" }] },
  { id: 'w119', text: 'ubiquitous', phonetic: '', pos: 'adj.', definition: 'present, appearing, or found everywhere', chinese: '无处不在的', categories: [], examples: [{ en: "Smartphones have become ubiquitous in modern society.", cn: "智能手机在现代社会中已无处不在。" }, { en: "The brand’s logo is ubiquitous in cities around the world.", cn: "该品牌的标志在世界各地的城市中随处可见。" }] },
  { id: 'w120', text: 'viable', phonetic: '', pos: 'adj.', definition: 'capable of working successfully; feasible', chinese: '可行的', categories: [], examples: [{ en: "The project is no longer viable due to lack of funding.", cn: "由于缺乏资金，该项目不再可行。" }, { en: "We need to find a viable solution to this problem.", cn: "我们需要找到这个问题的可行解决方案。" }] },

  // --- Group 2 (Locked) ---
  { id: 'w201', text: 'advocate', phonetic: '', pos: 'v.', definition: 'to publicly recommend or support', chinese: '倡导', categories: [], examples: [{ en: "She advocates for equal rights in the workplace.", cn: "她倡导工作场所的平等权利。" }, { en: "Many doctors advocate a balanced diet and regular exercise.", cn: "许多医生提倡均衡饮食和定期锻炼。" }] },
  { id: 'w202', text: 'bilateral', phonetic: '', pos: 'adj.', definition: 'involving two parties, especially countries', chinese: '双边的', categories: [], examples: [{ en: "The two nations signed a bilateral trade agreement.", cn: "两国签署了一项双边贸易协定。" }, { en: "Bilateral talks between the leaders are scheduled for next month.", cn: "两国领导人之间的双边会谈定于下个月举行。" }] },
  { id: 'w203', text: 'cognitive', phonetic: '', pos: 'adj.', definition: 'relating to the mental processes of understanding, learning, and remembering', chinese: '认知的', categories: [], examples: [{ en: "Cognitive development in early childhood is crucial for learning.", cn: "幼儿期的认知发展对学习至关重要。" }, { en: "The game is designed to improve cognitive skills like memory and attention.", cn: "这款游戏旨在提高记忆力和注意力等认知技能。" }] },
  { id: 'w204', text: 'delegate', phonetic: '', pos: 'v., n.', definition: 'v. to entrust (a task or responsibility) to another person; n. a person sent to represent others', chinese: '委派；代表', categories: [], examples: [{ en: "A good manager knows how to delegate tasks effectively.", cn: "一个好的经理知道如何有效地委派任务。" }, { en: "Each country sent a delegate to the international conference.", cn: "每个国家都派了一名代表参加这次国际会议。" }] },
  { id: 'w205', text: 'empirical', phonetic: '', pos: 'adj.', definition: 'based on observation or experience rather than theory', chinese: '经验的', categories: [], examples: [{ en: "The theory needs empirical evidence to be accepted.", cn: "这个理论需要经验证据才能被接受。" }, { en: "Empirical studies show that the treatment is effective.", cn: "实证研究表明该治疗是有效的。" }] },
  { id: 'w206', text: 'fiscal', phonetic: '', pos: 'adj.', definition: 'relating to government revenue, especially taxes', chinese: '财政的', categories: [], examples: [{ en: "The government’s fiscal policy aims to stimulate economic growth.", cn: "政府的财政政策旨在刺激经济增长。" }, { en: "The company is facing fiscal challenges due to increased costs.", cn: "由于成本增加，公司正面临财政挑战。" }] },
  { id: 'w207', text: 'gregarious', phonetic: '', pos: 'adj.', definition: 'fond of company; sociable', chinese: '爱交际的', categories: [], examples: [{ en: "She’s very gregarious and loves attending social events.", cn: "她非常爱交际，喜欢参加社交活动。" }, { en: "Gregarious animals, like wolves, live in packs.", cn: "群居动物，像狼一样，以群体生活。" }] },
  { id: 'w208', text: 'hierarchy', phonetic: '', pos: 'n.', definition: 'a system in which members of an organization are ranked according to status', chinese: '层级制度', categories: [], examples: [{ en: "The corporate hierarchy can sometimes slow down decision-making.", cn: "公司层级制度有时会拖慢决策速度。" }, { en: "In many cultures, there is a clear social hierarchy.", cn: "在许多文化中，存在明确的社会等级制度。" }] },
  { id: 'w209', text: 'incentive', phonetic: '', pos: 'n.', definition: 'a thing that motivates or encourages someone to do something', chinese: '激励', categories: [], examples: [{ en: "The company offers financial incentives to high-performing employees.", cn: "公司向表现优异的员工提供物质激励。" }, { en: "Tax breaks can be an incentive for businesses to invest in green technology.", cn: "税收减免可以激励企业投资绿色技术。" }] },
  { id: 'w210', text: 'jurisdiction', phonetic: '', pos: 'n.', definition: 'the official power to make legal decisions and judgments', chinese: '管辖权', categories: [], examples: [{ en: "This matter falls under the jurisdiction of the federal court.", cn: "此事属于联邦法院的管辖范围。" }, { en: "The police have no jurisdiction outside the city limits.", cn: "警方在城市范围外没有管辖权。" }] },
  { id: 'w211', text: 'kinetic', phonetic: '', pos: 'adj.', definition: 'relating to or resulting from motion', chinese: '动态的', categories: [], examples: [{ en: "The sculpture has a kinetic element that moves with the wind.", cn: "这座雕塑有一个随风运动的动态元素。" }, { en: "Kinetic energy is the energy an object possesses due to its motion.", cn: "动能是物体由于其运动而拥有的能量。" }] },
  { id: 'w212', text: 'leverage', phonetic: '', pos: 'n., v.', definition: 'n. the exertion of force by means of a lever; the power to influence; v. to use (something) to maximum advantage', chinese: '影响力', categories: [], examples: [{ en: "They used their political leverage to pass the bill.", cn: "他们利用政治影响力通过了该法案。" }, { en: "The company plans to leverage its brand to enter new markets.", cn: "公司计划利用其品牌进入新市场。" }] },
  { id: 'w213', text: 'metropolis', phonetic: '', pos: 'n.', definition: 'a very large and densely populated industrial and commercial city', chinese: '大都市', categories: [], examples: [{ en: "New York is a bustling metropolis with a diverse population.", cn: "纽约是一个人口多元、熙熙攘攘的大都市。" }, { en: "He moved from a small town to the metropolis in search of opportunities.", cn: "他从一个小镇搬到大都市寻找机会。" }] },
  { id: 'w214', text: 'nullify', phonetic: '', pos: 'v.', definition: 'to make legally null and void; invalidate', chinese: '宣告无效', categories: [], examples: [{ en: "The contract was nullified due to a breach of terms.", cn: "由于违反条款，合同被宣告无效。" }, { en: "The new evidence could nullify the previous verdict.", cn: "新证据可能使之前的判决无效。" }] },
  { id: 'w215', text: 'obsolete', phonetic: '', pos: 'adj.', definition: 'no longer produced or used; out of date', chinese: '过时的', categories: [], examples: [{ en: "Floppy disks have become obsolete with the rise of USB drives.", cn: "随着 U 盘的兴起，软盘已经过时了。" }, { en: "The technology they use is obsolete and inefficient.", cn: "他们使用的技术已经过时且效率低下。" }] },
  { id: 'w216', text: 'proliferate', phonetic: '', pos: 'v.', definition: 'to increase rapidly in number; multiply', chinese: '激增', categories: [], examples: [{ en: "Social media platforms have proliferated in the past decade.", cn: "社交媒体平台在过去十年中激增。" }, { en: "Without regulation, nuclear weapons could proliferate dangerously.", cn: "如果没有监管，核武器可能会危险地扩散。" }] },
  { id: 'w217', text: 'quandary', phonetic: '', pos: 'n.', definition: 'a state of perplexity or uncertainty over what to do in a difficult situation', chinese: '左右为难', categories: [], examples: [{ en: "She was in a quandary about whether to accept the job offer.", cn: "她对是否接受这份工作感到左右为难。" }, { en: "The team found themselves in a quandary when their funding was cut.", cn: "当资金被削减时，团队发现自己陷入了困境。" }] },
  { id: 'w218', text: 'redundant', phonetic: '', pos: 'adj.', definition: 'not or no longer needed or useful; superfluous', chinese: '多余的', categories: [], examples: [{ en: "His role became redundant after the company restructured.", cn: "公司重组后，他的职位变得多余了。" }, { en: "Avoid using redundant words in your writing.", cn: "写作中避免使用多余的词语。" }] },
  { id: 'w219', text: 'scrutinize', phonetic: '', pos: 'v.', definition: 'to examine or inspect closely and thoroughly', chinese: '仔细检查', categories: [], examples: [{ en: "The committee will scrutinize the proposal before making a decision.", cn: "委员会将在做出决定前仔细审查该提案。" }, { en: "Every document was scrutinized for errors.", cn: "每份文件都经过仔细检查以防出错。" }] },
  { id: 'w220', text: 'tangible', phonetic: '', pos: 'adj.', definition: 'perceptible by touch; clear and definite; real', chinese: '确凿的', categories: [], examples: [{ en: "The project needs tangible results to secure further investment.", cn: "该项目需要切实的成果来确保进一步投资。" }, { en: "There is no tangible evidence to support his claim.", cn: "没有确凿的证据支持他的说法。" }] },

  // --- Group 3 (Locked) ---
  { id: 'w301', text: 'ambivalent', phonetic: '', pos: 'adj.', definition: 'having mixed feelings or contradictory ideas about something or someone', chinese: '矛盾的', categories: [], examples: [{ en: "She felt ambivalent about moving abroad—excited but also anxious.", cn: "她对移居国外感到矛盾——既兴奋又焦虑。" }, { en: "He has an ambivalent attitude toward his new boss.", cn: "他对新老板的态度很矛盾。" }] },
  { id: 'w302', text: 'bureaucracy', phonetic: '', pos: 'n.', definition: 'a system of administration in which decisions are made by state officials rather than by elected representatives', chinese: '官僚制度', categories: [], examples: [{ en: "The bureaucracy often slows down the implementation of new policies.", cn: "官僚制度常常延缓新政策的实施。" }, { en: "Dealing with the local bureaucracy can be very frustrating.", cn: "与当地官僚机构打交道可能非常令人沮丧。" }] },
  { id: 'w303', text: 'catalyst', phonetic: '', pos: 'n.', definition: 'a substance that increases the rate of a chemical reaction without itself undergoing any permanent change; a person or thing that causes change', chinese: '催化剂', categories: [], examples: [{ en: "The new policy acted as a catalyst for economic growth.", cn: "新政策成为经济增长的催化剂。" }, { en: "She was the catalyst that brought the team together.", cn: "她是让团队凝聚起来的促成因素。" }] },
  { id: 'w304', text: 'dichotomy', phonetic: '', pos: 'n.', definition: 'a division or contrast between two things that are opposed or entirely different', chinese: '二分法', categories: [], examples: [{ en: "There is a clear dichotomy between theory and practice.", cn: "理论与实践之间存在明显的二分法。" }, { en: "The film explores the dichotomy between good and evil.", cn: "这部电影探讨了善与恶的对立。" }] },
  { id: 'w305', text: 'ephemeral', phonetic: '', pos: 'adj.', definition: 'lasting for a very short time', chinese: '短暂的', categories: [], examples: [{ en: "The beauty of cherry blossoms is ephemeral.", cn: "樱花的美丽是短暂的。" }, { en: "Social media trends are often ephemeral.", cn: "社交媒体趋势往往是短暂的。" }] },
  { id: 'w306', text: 'frugal', phonetic: '', pos: 'adj.', definition: 'sparing or economical with regard to money or food', chinese: '节俭的', categories: [], examples: [{ en: "Despite being wealthy, he leads a frugal lifestyle.", cn: "尽管富有，他仍过着节俭的生活。" }, { en: "She is frugal with her spending to save for a house.", cn: "她为了攒钱买房，在开支上很节俭。" }] },
  { id: 'w307', text: 'garrulous', phonetic: '', pos: 'adj.', definition: 'excessively talkative, especially on trivial matters', chinese: '话多的', categories: [], examples: [{ en: "The garrulous taxi driver talked nonstop throughout the ride.", cn: "那个喋喋不休的出租车司机一路上说个不停。" }, { en: "She avoided sitting next to the garrulous colleague in meetings.", cn: "开会时她避免坐在那个话多的同事旁边。" }] },
  { id: 'w308', text: 'hedge', phonetic: '', pos: 'v., n.', definition: 'v. to limit or qualify (something) by conditions or exceptions; to avoid making a definite statement or commitment; n. a fence or boundary formed by closely growing bushes or shrubs', chinese: '规避风险', categories: [], examples: [{ en: "Investors often hedge their bets by diversifying their portfolios.", cn: "投资者通常通过分散投资组合来规避风险。" }, { en: "The garden was surrounded by a tall hedge.", cn: "花园被一道高高的树篱围住。" }] },
  { id: 'w309', text: 'ideology', phonetic: '', pos: 'n.', definition: 'a system of ideas and ideals, especially one which forms the basis of economic or political theory and policy', chinese: '意识形态', categories: [], examples: [{ en: "Political parties often have different ideologies.", cn: "政党通常有不同的意识形态。" }, { en: "The company's ideology emphasizes innovation and teamwork.", cn: "公司的理念强调创新与团队合作。" }] },
  { id: 'w310', text: 'jargon', phonetic: '', pos: 'n.', definition: 'special words or expressions used by a profession or group that are difficult for others to understand', chinese: '术语', categories: [], examples: [{ en: "The doctor's explanation was full of medical jargon.", cn: "医生的解释充满了医学术语。" }, { en: "Try to avoid using too much jargon in your presentation.", cn: "在你的演示中尽量避免使用太多行话。" }] },
  { id: 'w311', text: 'lucid', phonetic: '', pos: 'adj.', definition: 'expressed clearly; easy to understand', chinese: '清晰的', categories: [], examples: [{ en: "She gave a lucid explanation of the complex topic.", cn: "她对那个复杂话题做了清晰的解释。" }, { en: "His writing is always lucid and engaging.", cn: "他的写作总是清晰而引人入胜。" }] },
  { id: 'w312', text: 'meritocracy', phonetic: '', pos: 'n.', definition: 'a system in which advancement is based on individual ability or achievement', chinese: '精英制度', categories: [], examples: [{ en: "The company prides itself on being a meritocracy.", cn: "公司以其精英制度为傲。" }, { en: "In a true meritocracy, everyone has an equal chance to succeed.", cn: "在真正的精英制度中，每个人都有平等的成功机会。" }] },
  { id: 'w313', text: 'notorious', phonetic: '', pos: 'adj.', definition: 'famous or well known, typically for some bad quality or deed', chinese: '臭名昭著的', categories: [], examples: [{ en: "The area is notorious for its high crime rate.", cn: "该地区因其高犯罪率而臭名昭著。" }, { en: "He is a notorious gambler.", cn: "他是个声名狼藉的赌徒。" }] },
  { id: 'w314', text: 'orthodox', phonetic: '', pos: 'adj.', definition: 'conforming to what is generally or traditionally accepted as right or true', chinese: '正统的', categories: [], examples: [{ en: "He follows orthodox methods in his research.", cn: "他在研究中遵循正统方法。" }, { en: "Orthodox medicine sometimes clashes with alternative therapies.", cn: "正统医学有时与替代疗法相冲突。" }] },
  { id: 'w315', text: 'precarious', phonetic: '', pos: 'adj.', definition: 'not securely held or in position; dangerously likely to fall or collapse', chinese: '不稳定的', categories: [], examples: [{ en: "He find himself in a precarious financial situation.", cn: "他发现自己处于不稳定的财务状况中。" }, { en: "The ladder was in a precarious position against the wall.", cn: "梯子靠在墙上，位置很危险。" }] },
  { id: 'w316', text: 'quota', phonetic: '', pos: 'n.', definition: 'a limited or fixed number or amount of people or things', chinese: '配额', categories: [], examples: [{ en: "The factory has a daily production quota to meet.", cn: "工厂有每日生产配额要完成。" }, { en: "The country has imposed an import quota on foreign cars.", cn: "该国对外国汽车实施了进口配额。" }] },
  { id: 'w317', text: 'reconcile', phonetic: '', pos: 'v.', definition: 'to restore friendly relations between; to make compatible', chinese: '使一致', categories: [], examples: [{ en: "It took them years to reconcile after their argument.", cn: "争吵后，他们花了好几年才和好。" }, { en: "How do you reconcile your beliefs with your actions?", cn: "你如何使你的信念与行动保持一致？" }] },
  { id: 'w318', text: 'substantiate', phonetic: '', pos: 'v.', definition: 'to provide evidence to support or prove the truth of', chinese: '证实', categories: [], examples: [{ en: "Can you substantiate your claim with data?", cn: "你能用数据来证实你的说法吗？" }, { en: "The witness’s testimony helped substantiate the case.", cn: "证人的证词有助于证实这个案件。" }] },
  { id: 'w319', text: 'tacit', phonetic: '', pos: 'adj.', definition: 'understood or implied without being stated', chinese: '默许的', categories: [], examples: [{ en: "There was a tacit agreement that they would share the profits.", cn: "他们之间有一个心照不宣的协议，即分享利润。" }, { en: "His silence was taken as tacit approval.", cn: "他的沉默被理解为默许。" }] },
  { id: 'w320', text: 'versatile', phonetic: '', pos: 'adj.', definition: 'able to adapt or be adapted to many different functions or activities', chinese: '多功能性的', categories: [], examples: [{ en: "She is a versatile actress who can play both drama and comedy.", cn: "她是一位多才多艺的女演员，既能演戏剧也能演喜剧。" }, { en: "This tool is versatile and can be used for various tasks.", cn: "这个工具功能多样，可用于各种任务。" }] },

  // --- Group 4 (Locked) ---
  { id: 'w401', text: 'articulate', phonetic: '', pos: 'v., adj.', definition: 'v. to express (an idea or feeling) fluently and coherently; adj. having or showing the ability to speak fluently and coherently', chinese: '清楚地表达', categories: [], examples: [{ en: "She articulated her concerns clearly during the meeting.", cn: "她在会议上清楚地表达了自己的担忧。" }, { en: "He is an articulate speaker who can engage any audience.", cn: "他是一位口才好的演讲者，能吸引任何观众。" }] },
  { id: 'w402', text: 'brevity', phonetic: '', pos: 'n.', definition: 'concise and exact use of words in writing or speech', chinese: '简洁', categories: [], examples: [{ en: "The report was praised for its clarity and brevity.", cn: "报告因其清晰和简洁而受到赞扬。" }, { en: "Brevity is the soul of wit.", cn: "简洁是智慧的灵魂。" }] },
  { id: 'w403', text: 'contingency', phonetic: '', pos: 'n.', definition: 'a future event or circumstance which is possible but cannot be predicted with certainty', chinese: '应急计划', categories: [], examples: [{ en: "We have a contingency plan in case of bad weather.", cn: "我们有一个应急计划以防恶劣天气。" }, { en: "The budget includes a contingency for unexpected expenses.", cn: "预算中包含了应对意外支出的应急费用。" }] },
  { id: 'w404', text: 'diligent', phonetic: '', pos: 'adj.', definition: 'having or showing care and conscientiousness in one\'s work or duties', chinese: '勤奋的', categories: [], examples: [{ en: "She is a diligent student who always completes her homework on time.", cn: "她是一个勤奋的学生，总是按时完成作业。" }, { en: "His diligent efforts led to the project\'s success.", cn: "他勤勉的努力促成了项目的成功。" }] },
  { id: 'w405', text: 'elaborate', phonetic: '', pos: 'v., adj.', definition: 'v. to develop or present (a theory, policy, or system) in detail; adj. involving many carefully arranged parts or details; detailed and complicated', chinese: '详细阐述', categories: [], examples: [{ en: "Could you elaborate on your proposal?", cn: "你能详细阐述一下你的提案吗？" }, { en: "The wedding cake had an elaborate design.", cn: "婚礼蛋糕有一个复杂的设计。" }] },
  { id: 'w406', text: 'fluctuate', phonetic: '', pos: 'v.', definition: 'to rise and fall irregularly in number or amount', chinese: '波动', categories: [], examples: [{ en: "Stock prices fluctuate based on market conditions.", cn: "股价根据市场状况波动。" }, { en: "Her mood seems to fluctuate from day to day.", cn: "她的情绪似乎每天都在波动。" }] },
  { id: 'w407', text: 'galvanize', phonetic: '', pos: 'v.', definition: 'to shock or excite (someone) into taking action', chinese: '激励', categories: [], examples: [{ en: "The speech galvanized the crowd into action.", cn: "演讲激励了人群采取行动。" }, { en: "The crisis galvanized the government to implement reforms.", cn: "危机刺激政府实施了改革。" }] },
  { id: 'w408', text: 'holistic', phonetic: '', pos: 'adj.', definition: 'characterized by the belief that the parts of something are interconnected and can be explained only by reference to the whole', chinese: '整体的', categories: [], examples: [{ en: "The clinic takes a holistic approach to health, focusing on mind and body.", cn: "诊所采取整体健康方法，关注身心。" }, { en: "We need a holistic strategy to address environmental issues.", cn: "我们需要一个全面的战略来解决环境问题。" }] },
  { id: 'w409', text: 'impede', phonetic: '', pos: 'v.', definition: 'to delay or prevent (someone or something) by obstructing them; hinder', chinese: '阻碍', categories: [], examples: [{ en: "Heavy traffic impeded our progress to the airport.", cn: "交通拥堵阻碍了我们前往机场的进程。" }, { en: "Bureaucracy can impede innovation in large organizations.", cn: "官僚制度可能阻碍大型组织中的创新。" }] },
  { id: 'w410', text: 'jeopardize', phonetic: '', pos: 'v.', definition: 'to put (something or someone) into a situation of risk or danger', chinese: '危及', categories: [], examples: [{ en: "Smoking can jeopardize your health.", cn: "吸烟可能危害你的健康。" }, { en: "He didn’t want to jeopardize his career by making a controversial statement.", cn: "他不想因发表有争议的言论而危及自己的职业生涯。" }] },
  { id: 'w411', text: 'liaise', phonetic: '', pos: 'v.', definition: 'to cooperate on a matter of mutual concern', chinese: '紧密联系', categories: [], examples: [{ en: "Our department liaises closely with the marketing team.", cn: "我们部门与市场团队紧密联系。" }, { en: "She will liaise between the clients and the developers.", cn: "她将在客户和开发人员之间进行联络。" }] },
  { id: 'w412', text: 'mandatory', phonetic: '', pos: 'adj.', definition: 'required by law or rules; compulsory', chinese: '强制的', categories: [], examples: [{ en: "Wearing a helmet is mandatory for cyclists in this city.", cn: "在这个城市，骑自行车必须戴头盔。" }, { en: "Attendance at the safety briefing is mandatory for all employees.", cn: "所有员工都必须参加安全简报会。" }] },
  { id: 'w413', text: 'nostalgic', phonetic: '', pos: 'adj.', definition: 'characterized by or exhibiting feelings of nostalgia', chinese: '怀旧的', categories: [], examples: [{ en: "Seeing her old school photos made her feel nostalgic.", cn: "看到她以前的学校照片让她感到怀旧。" }, { en: "The film has a nostalgic charm that appeals to older audiences.", cn: "这部电影有一种怀旧的魅力，吸引着年长的观众。" }] },
  { id: 'w414', text: 'opaque', phonetic: '', pos: 'adj.', definition: 'not able to be seen through; not transparent; difficult to understand', chinese: '晦涩难懂的', categories: [], examples: [{ en: "The windows were made of opaque glass for privacy.", cn: "窗户采用不透明的玻璃以保护隐私。" }, { en: "His explanation was so opaque that nobody understood it.", cn: "他的解释晦涩难懂，没人能理解。" }] },
  { id: 'w415', text: 'prolific', phonetic: '', pos: 'adj.', definition: '(of a plant, animal, or person) producing much fruit or foliage or many offspring; (of an artist, author, or composer) producing many works', chinese: '多产的', categories: [], examples: [{ en: "She is a prolific writer, having published over twenty novels.", cn: "她是一位多产的作家，已出版了二十多部小说。" }, { en: "The region is known for its prolific vineyards.", cn: "该地区以其多产的葡萄园而闻名。" }] },
  { id: 'w416', text: 'quarantine', phonetic: '', pos: 'n., v.', definition: 'a state, period, or place of isolation in which people or animals that may have been exposed to infectious disease are placed', chinese: '隔离', categories: [], examples: [{ en: "Travelers from affected areas were placed in quarantine.", cn: "来自受影响地区的旅客被隔离。" }, { en: "The dog had to be quarantined for two weeks after arriving.", cn: "狗在到达后必须被隔离两周。" }] },
  { id: 'w417', text: 'revitalize', phonetic: '', pos: 'v.', definition: 'to imbue (something) with new life and vitality', chinese: '注入新活力', categories: [], examples: [{ en: "The new investment will revitalize the local economy.", cn: "新投资将为当地经济注入新活力。" }, { en: "They plan to revitalize the old neighborhood.", cn: "他们计划振兴旧街区。" }] },
  { id: 'w418', text: 'scrutiny', phonetic: '', pos: 'n.', definition: 'critical observation or examination', chinese: '审视', categories: [], examples: [{ en: "The proposal will face intense scrutiny from the committee.", cn: "该提案将面临委员会的严格审查。" }, { en: "Celebrities are often under public scrutiny.", cn: "名人常常受到公众的审视。" }] },
  { id: 'w419', text: 'transparent', phonetic: '', pos: 'adj.', definition: 'allowing light to pass through so that objects behind can be distinctly seen; easy to perceive or detect', chinese: '透明的', categories: [], examples: [{ en: "The government promised more transparent decision-making.", cn: "政府承诺决策将更加透明。" }, { en: "The water was so transparent we could see the fish clearly.", cn: "水如此清澈，我们能清楚地看到鱼。" }] },
  { id: 'w420', text: 'unanimous', phonetic: '', pos: 'adj.', definition: '(of two or more people) fully in agreement', chinese: '一致的', categories: [], examples: [{ en: "The decision was unanimous among the board members.", cn: "董事会成员一致做出了这个决定。" }, { en: "They reached a unanimous verdict after hours of deliberation.", cn: "经过数小时的审议，他们达成了一致裁决。" }] },

  // --- Group 5 & 6 (Restored) ---
  { id: 'w501', text: 'analogy', phonetic: '', pos: 'n.', definition: 'a comparison between two things for clarification', chinese: '类比', categories: [], examples: [{ en: "He used an analogy of a car engine to explain how the heart works.", cn: "他用汽车引擎的类比来解释心脏的工作原理。" }, { en: "The analogy between the human brain and a computer is often made.", cn: "人脑与计算机之间的类比经常被提及。" }] },
  { id: 'w601', text: 'aesthetic', phonetic: '', pos: 'adj., n.', definition: 'concerned with beauty or the appreciation of beauty', chinese: '审美的', categories: [], examples: [{ en: "The building’s aesthetic design won several awards.", cn: "这座建筑的审美设计赢得了多个奖项。" }, { en: "Her aesthetic is minimalist and modern.", cn: "她的审美是极简和现代的。" }] },

  // --- Group 10 (Locked) ---
  { id: 'w1001', text: 'aberration', phonetic: '/ˌæbəˈreɪʃn/', pos: 'n.', definition: 'A departure from what is normal, usual, or expected.', chinese: '偏差；反常现象', categories: ['科技', '专八'], examples: [{ en: "The sudden spike in temperature was a statistical aberration.", cn: "这次温度的突然飙升是统计偏差。" }, { en: "His outburst of anger was an aberration from his normal demeanor.", cn: "他这次发怒是一次反常行为。" }] },
  { id: 'w1010', text: 'kinship', phonetic: '/ˈkɪnʃɪp/', pos: 'n.', definition: 'Blood relationship; a feeling of closeness.', chinese: '亲属关系', categories: ['文化'], examples: [{ en: "They felt a strong kinship due to their shared cultural heritage.", cn: "他们因共同的文化遗产而感到亲切。" }, { en: "The project fostered a sense of kinship among team members.", cn: "项目在团队成员间培养了亲密感。" }] },

  // --- Group 11 (Restored) ---
  { id: 'w1101', text: 'articulate', phonetic: '/ɑːˈtɪkjuleɪt/', pos: 'v./adj.', definition: 'To express fluently and coherently.', chinese: '清晰表达', categories: ['专八'], examples: [{ en: "She struggled to articulate her complex feelings.", cn: "她难以清晰表达复杂的感受。" }, { en: "He is an articulate speaker.", cn: "他是一个口才很好的演讲者。" }] },
  { id: 'w1102', text: 'bolster', phonetic: '/ˈbəʊlstə(r)/', pos: 'v.', definition: 'To support or strengthen; to prop up.', chinese: '支持', categories: ['商务'], examples: [{ en: "Positive sales figures bolstered investor confidence.", cn: "销售数据增强了投资者信心。" }, { en: "She drank coffee to bolster her energy.", cn: "她喝咖啡来提振精神。" }] },
  { id: 'w1103', text: 'concise', phonetic: '/kənˈsaɪs/', pos: 'adj.', definition: 'Giving a lot of information clearly and in a few words.', chinese: '简明的', categories: ['通用'], examples: [{ en: "Please keep your report concise.", cn: "请让你的报告简明扼要。" }, { en: "A concise summary was provided.", cn: "提供了一个简洁的概要。" }] },
  { id: 'w1104', text: 'delineate', phonetic: '/dɪˈlɪnieɪt/', pos: 'v.', definition: 'To describe or portray something precisely.', chinese: '描绘', categories: ['专八'], examples: [{ en: "The contract clearly delineates the responsibilities.", cn: "合同明确规定了各方的责任。" }, { en: "The author delineates the social landscape.", cn: "作者描绘了社会风貌。" }] },
  { id: 'w1110', text: 'juxtaposition', phonetic: '/ˌdʒʌkstəpəˈzɪʃn/', pos: 'n.', definition: 'Two things being seen or placed close together with contrasting effect.', chinese: '并置', categories: ['文化'], examples: [{ en: "The juxtaposition of modern and ancient ruins is striking.", cn: "现代与古代遗迹的并置产生了视觉对比。" }, { en: "The film uses juxtaposition to highlight differences.", cn: "电影运用并列手法来突显差异。" }] },
  { id: 'w1120', text: 'verbose', phonetic: '/vɜːˈbəʊs/', pos: 'adj.', definition: 'Using more words than are needed.', chinese: '冗长的', categories: ['专八'], examples: [{ en: "The instruction manual was verbose.", cn: "说明书太冗长啰嗦了。" }, { en: "His verbose writing style made a simple idea complex.", cn: "他冗长的写作风格让想法变得复杂。" }] },

  // --- Group 12 (Restored) ---
  { id: 'w1201', text: 'amorphous', phonetic: '/əˈmɔːfəs/', pos: 'adj.', definition: 'Without a clearly defined shape or form.', chinese: '无定形的', categories: ['科技'], examples: [{ en: "The artist worked with amorphous blobs of clay.", cn: "艺术家使用无定形的黏土块进行创作。" }, { en: "The strategy was still amorphous.", cn: "策略仍然模糊不清。" }] },
  { id: 'w1202', text: 'bureaucracy', phonetic: '/bjʊəˈrɒkrəsi/', pos: 'n.', definition: 'A system of government with many state officials.', chinese: '官僚制度', categories: ['商务'], examples: [{ en: "Navigating the bureaucracy can be slow.", cn: "走政府程序可能是一个缓慢的过程。" }, { en: "The startup aimed to disrupt the bureaucracy.", cn: "初创公司旨在通过打破官僚体系来颠覆行业。" }] },
  { id: 'w1203', text: 'catalyst', phonetic: '/ˈkætəlɪst/', pos: 'n.', definition: 'A substance that increases the rate of a reaction.', chinese: '催化剂', categories: ['科技'], examples: [{ en: "The internet served as a catalyst for globalization.", cn: "互联网的发明是全球化的催化剂。" }, { en: "Her speech acted as a catalyst.", cn: "她的演讲起到了催化剂的作用。" }] },
  { id: 'w1214', text: 'paradigm', phonetic: '/ˈpærədaɪm/', pos: 'n.', definition: 'A typical example or pattern; a model.', chinese: '范式', categories: ['科技'], examples: [{ en: "The discovery represented a paradigm shift.", cn: "这一发现代表了重大的范式转变。" }, { en: "This study challenges the prevailing paradigm.", cn: "这项研究挑战了主流范式。" }] },
  { id: 'w1220', text: 'watershed', phonetic: '/ˈwɔːtəshed/', pos: 'n.', definition: 'An event marking a turning point.', chinese: '分水岭', categories: ['文化'], examples: [{ en: "The printing press was a watershed moment.", cn: "印刷术的发明是一个分水岭式的时刻。" }, { en: "The ruling marked a watershed for rights.", cn: "裁决标志着权利斗争的一个转折点。" }] },

  // --- Group 13 (Restored Full) ---
  { id: 'w1301', text: 'hypothesis', phonetic: '/haɪˈpɒθəsɪs/', pos: 'n.', definition: 'A proposed explanation based on limited evidence.', chinese: '假设', categories: [], examples: [{ en: "The researcher's hypothesis was that sleep deprivation would impair memory.", cn: "" }, { en: "We need to test this hypothesis with an experiment.", cn: "" }] },
  { id: 'w1302', text: 'synthesize', phonetic: '/ˈsɪnθəsaɪz/', pos: 'v.', definition: 'To combine components into a coherent whole.', chinese: '综合', categories: [], examples: [{ en: "A good review synthesizes sources.", cn: "" }, { en: "The challenge is to synthesize information.", cn: "" }] },
  { id: 'w1305', text: 'critical thinking', phonetic: '/ˈkrɪtɪkəl ˈθɪŋkɪŋ/', pos: 'n.', definition: 'Objective analysis to form a judgment.', chinese: '批判性思维', categories: [], examples: [{ en: "Universities aim to foster critical thinking.", cn: "" }, { en: "Critical thinking is essential for discerning information.", cn: "" }] },
  { id: 'w1312', text: 'paradigm', phonetic: '/ˈpærədaɪm/', pos: 'n.', definition: 'A typical example; a worldview.', chinese: '范式', categories: [], examples: [{ en: "Einstein's theory caused a paradigm shift.", cn: "" }, { en: "The study challenges the current paradigm.", cn: "" }] },
  { id: 'w1320', text: 'quintessential', phonetic: '/ˌkwɪntɪˈsenʃl/', pos: 'adj.', definition: 'Representing the most perfect example.', chinese: '精髓的', categories: [], examples: [{ en: "The cafe was the quintessential Parisian experience.", cn: "" }, { en: "He is the quintessential team player.", cn: "" }] },

  // --- Group 14 (Restored Full) ---
  { id: 'w1401', text: 'revenue', phonetic: '/ˈrevənjuː/', pos: 'n.', definition: 'Income of a company or organization.', chinese: '营收', categories: [], examples: [{ en: "Annual revenue exceeded one billion dollars.", cn: "" }, { en: "Advertising is the primary source of revenue.", cn: "" }] },
  { id: 'w1405', text: 'entrepreneur', phonetic: '/ˌɒntrəprəˈnɜː(r)/', pos: 'n.', definition: 'A person who starts a business for profit.', chinese: '企业家', categories: [], examples: [{ en: "She is a successful entrepreneur.", cn: "" }, { en: "The government launched a scheme for young entrepreneurs.", cn: "" }] },
  { id: 'w1418', text: 'recession', phonetic: '/rɪˈseʃn/', pos: 'n.', definition: 'A period of temporary economic decline.', chinese: '经济衰退', categories: [], examples: [{ en: "The financial crisis triggered a recession.", cn: "" }, { en: "The country managed to avert a recession.", cn: "" }] },

  // --- Group 15 (Restored Full) ---
  { id: 'w1501', text: 'algorithm', phonetic: '/ˈælɡərɪðəm/', pos: 'n.', definition: 'A process or set of rules followed by a computer.', chinese: '算法', categories: [], examples: [{ en: "The search engine uses a complex algorithm.", cn: "" }, { en: "Social media algorithms create filter bubbles.", cn: "" }] },
  { id: 'w1506', text: 'artificial intelligence (ai)', phonetic: '/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/', pos: 'n.', definition: 'Development of systems able to perform human tasks.', chinese: '人工智能', categories: [], examples: [{ en: "AI is transforming healthcare and finance.", cn: "" }, { en: "Ethical guidelines for AI are needed.", cn: "" }] },
  { id: 'w1512', text: 'cryptocurrency', phonetic: '/ˈrɪptəʊkʌrənsi/', pos: 'n.', definition: 'Digital currency verified using cryptography.', chinese: '加密货币', categories: [], examples: [{ en: "Bitcoin is the most well-known cryptocurrency.", cn: "" }, { en: "Volatility attracts both investors and speculators.", cn: "" }] }
];

export const GROUPS: WordGroup[] = [
  { id: 'g1', title: '第 1 组', words: ['w101', 'w102', 'w103', 'w104', 'w105', 'w106', 'w107', 'w108', 'w109', 'w110', 'w111', 'w112', 'w113', 'w114', 'w115', 'w116', 'w117', 'w118', 'w119', 'w120'], locked: true },
  { id: 'g2', title: '第 2 组', words: ['w201', 'w202', 'w203', 'w204', 'w205', 'w206', 'w207', 'w208', 'w209', 'w210', 'w211', 'w212', 'w213', 'w214', 'w215', 'w216', 'w217', 'w218', 'w219', 'w220'], locked: true },
  { id: 'g3', title: '第 3 组', words: ['w301', 'w302', 'w303', 'w304', 'w305', 'w306', 'w307', 'w308', 'w309', 'w310', 'w311', 'w312', 'w313', 'w314', 'w315', 'w316', 'w317', 'w318', 'w319', 'w320'], locked: true },
  { id: 'g4', title: '第 4 组', words: ['w401', 'w402', 'w403', 'w404', 'w405', 'w406', 'w407', 'w408', 'w409', 'w410', 'w411', 'w412', 'w413', 'w414', 'w415', 'w416', 'w417', 'w418', 'w419', 'w420'], locked: true },
  { id: 'g5', title: '第 5 组', words: ['w501'], locked: true },
  { id: 'g6', title: '第 6 组', words: ['w601'], locked: true },
  { id: 'g10', title: '第 10 组', words: ['w1001', 'w1010'], locked: true },
  { id: 'g11', title: '第 11 组', words: ['w1101', 'w1102', 'w1103', 'w1104', 'w1110', 'w1120'], locked: true },
  { id: 'g12', title: '第 12 组', words: ['w1201', 'w1202', 'w1203', 'w1214', 'w1220'], locked: true },
  { id: 'g13', title: '第 13 组', words: ['w1301', 'w1302', 'w1305', 'w1312', 'w1320'], locked: true },
  { id: 'g14', title: '第 14 组', words: ['w1401', 'w1405', 'w1418'], locked: true },
  { id: 'g15', title: '第 15 组', words: ['w1501', 'w1506', 'w1512'], locked: true }
];

export const CATEGORIES = [
  '大学英语四级', '大学英语六级', '专四', '专八', '雅思', '商务英语', '金融', '科技', '文化', '社交'
];

export const ARTICLES: Article[] = [
  {
    id: 'a1',
    title: 'The Future of AI in Modern Education',
    category: 'Tech',
    summary: 'Exploring how artificial intelligence is reshaping the classroom experience.',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800',
    paragraphs: [
      { en: "Artificial intelligence is no longer a futuristic concept; it is already transforming how we learn and teach. From personalized learning platforms to AI-driven grading systems, the educational landscape is evolving rapidly.", cn: "人工智能不再是一个未来的概念；它已经在改变我们的学习和教学方式。从个性化学习平台到人工智能驱动的评分系统，教育格局正在迅速演变。" },
      { en: "However, the rise of AI also brings challenges. Educators must ensure that technology complements human instruction rather than replacing it, focusing on critical thinking and emotional intelligence.", cn: "然而，人工智能的兴起也带来了挑战。教育工作者必须确保技术是作为人类教学的补充而不是替代，重点关注批判性思维和情商。" }
    ],
    keywords: [ { text: 'Artificial Intelligence', cn: '人工智能' }, { text: 'Transforming', cn: '变革' }, { text: 'Landscape', cn: '格局/图景' }, { text: 'Complement', cn: '补充' } ]
  }
];
